### PR TITLE
Added Runtime permission to support API 23

### PR DESCRIPTION
**Pull request by prof18**
Added Runtime permission to support API 23

### CODE REVIEW

**Comment by anlif** [comment]
Why did you add so many files?

**Comment by prof18** [comment]
Oh, that's true..There are only generated file; Probably I didn't configured well the gitignore

**Comment by prof18** [comment]
*There are lot's of generated file

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!

**Pull request closed without merging**
