### PR TITLE
Show `ProgressDialog` while reconnecting to a device from the `DeviceControlActivity`

### PR DESCRIPTION
**Pull request by tfKamran**
Fixes issue #8

---
This change is [Reviewable](https://reviewable.io/reviews/googlesamples/android-bluetoothlegatt/9)

### CODE REVIEW

**Comment by tfKamran** [comment]
I've already signed it, if not my email account, then at least my GitHub username should have matched.

**Comment by mitchross** [comment]
@tfKamran  you need to reply "I signed it!"

**Comment by ryanseys** [comment]
No, some of the commits just don't have an email (you can see this by seeing the commits aren't associated with an email in the commits panel of this PR).

Or just look at https://github.com/googlesamples/android-BluetoothLeGatt/commit/3556ca61044c4ddf49317c0ab9c8c4897e1657c9.patch and see that the commit doesn't have an email in the From field.

screen shot 2016-03-21 at 1 47 53 pm

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!

**Pull request closed without merging**
